### ISSUE TITLE
Logo For Taste That

### ISSUE THREAD

**Issue by zularizal** [Stoyan-Ivanov/TasteThat#2]
Hello @Stoyan-Ivanov  , I am a graphic designer, I want to help you in graphic design.

After I review your project is great, but you have not a logo/icon on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. And it's free for you. What do you think?

**Comment by Stoyan-Ivanov** [comment]
Hi @zularizal !
That would be awesome! Feel free to make a pull request. I really appreciate your interest in the project.

**Comment by zularizal** [comment]
Hi @Stoyan-Ivanov , I have a question, what is this app about? And what is the purpose of this application?

**Comment by zularizal** [comment]
Hi, I've made 3 pieces of sample logo, what do you think? is there anything you want to change?
![g4428](https://user-images.githubusercontent.com/38547278/40947136-5acff084-688b-11e8-95d1-334af2944eea.png)

**Comment by zularizal** [comment]
What do you think @Stoyan-Ivanov ?

**Comment by Stoyan-Ivanov** [comment]
Hi @zularizal! The icons look awesome! I like all of them but I feel like the third one (with the single T) will fit perfectly the app context.

**Comment by zularizal** [comment]
Hi @Stoyan-Ivanov , I've uploaded logo and icon to drive, this is the link ..

https://drive.google.com/open?id=1vyOevkz44utpk_sSnPVQyLQgcEinwEE_

And also I have sent a pull request for you, please check #3

**Comment by Stoyan-Ivanov** [comment]
Hi @zularizal , I did merge the pull request but can you share a shareable link for the drive because it doesn't give me access to it. Thank you for the effort!

**Comment by zularizal** [comment]
Sorry, This is the link

[Drive Link](https://drive.google.com/drive/u/2/folders/1vyOevkz44utpk_sSnPVQyLQgcEinwEE_)

**Comment by zularizal** [comment]
Okay, I will close this issue
